jobs:
  build:
    docker:
      - image: cimg/php:8.1-node

    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: composer install -n --prefer-dist
      - run: php artisan key:generate --env=testing
      - run: php artisan migrate:fresh --seed
      # - run: npm ci --prefix /home/circleci/project/backend
      # - run: npm run dev --prefix /home/circleci/project/backend
      - run:
          name: laravel test
          command: php artisan test