version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:8-node-browsers-legacy
    steps:
      - checkout
      - run: composer install -n --prefer-dist --working-dir=/home/circleci/project/backend
      - run: npm ci
      - run: npm run dev
      - run:
          name: laravel test
          command: php artisan test